<?php 
    echo $this->doctype(); 
    $children = $this->viewModel()->getCurrent()->getChildren();
    $child = $children[0];
    
?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <title>Optimus Summary Automation</title>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        // ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) 
                         ->prependStylesheet($this->basePath('css/datetimepicker.css'))?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/datetimepicker.js'))
            ->prependFile($this->basePath('js/moment.js'))
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
        ; ?>

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker12').datetimepicker({
                inline: true,
                sideBySide: true
            });
        });
    </script>
    <script type="text/javascript">
    $(document).ready(function(){
        $('.datepicker').removeClass('col-md-6');
        $('.datepicker').addClass('col-md-12');

        $('#right-sidebar-panel-link').panelslider({
                side: 'right',
                clickClose: false,
                duration: 200
        });

        $('#right-sidebar-panel-link').on('click', function() {
            $(this).toggleClass('active-right-panel');
            if ($('.active-right-panel').length) {
                $('<div class="overlay" />').insertBefore($(this));
            } else {
                $('.overlay').remove();
            }
        });
    });
    </script>

    </head>
    <body>
    <div class="container-fluid">
    <div class="row t-header">
     <?php
                        if(isset($child->session))
                        {
                    ?>
                <header class="t-header__wrapper">
                    <div class="c-logo col-xs-3 col-sm-4 col-md-7 col-lg-8">
                        <a href="#">
                            <img src="img/logo.png" />
                        </a>
                    </div>
                   
                            <div class="c-right-menu col-xs-9 col-sm-8 col-md-5 col-lg-4 text-right">
                                <ul class="list-inline c-right-menu__link">
                                    <li>
                                        <a href="#"><span>Hello</span> Amit Gupta</a>
                                    </li>
                                    <li>
                                        <a href="#">Setting</a>
                                    </li>
                                    <li>
                                        <a href="#">Logout</a>
                                    </li>
                                </ul>

                                <p class="c-right-menu__last-login-details text-left">Last Login 31st July 2015</p>
                            </div>
                   
                    
                </header>
                 <?php
                        }
                    ?>
                <?php
                    if(isset($child->session))
                    {
                ?>
                <nav class="navbar navbar-default col-xs-12 col-sm-12 col-md-12 c-navigation">
                
                        <div class="container-fluid">
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header hidden-sm hidden-md hidden-lg">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>

                                <a class="navbar-brand" href="#">Navigation</a>
                            </div>

                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="#">Dashboard <span class="sr-only">(current)</span></a></li>
                                    <li><a href="#">User</a></li>
                                    <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#">Action</a></li>
                                            <li><a href="#">Another action</a></li>
                                            <li><a href="#">Something else here</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="#">Separated link</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="#">One more separated link</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">Modules</a></li>
                                    <li><a href="#">Settings</a></li>
                                </ul>

                                <form class="navbar-form navbar-left c-search-form" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                    </div>
                                    <button type="submit" class="btn btn-default glyphicon glyphicon-search c-search-btn"></button>
                                </form>

                            </div><!-- /.navbar-collapse -->
                        </div><!-- /.container-fluid -->
                </nav>
                <?php
                        }
                    ?>
            </div> <!-- End t-header -->
            <div class="row t-main">
                <?php echo $this->content; ?>
           
            </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>

        </div>
       
    </body>
</html>
