
    <div class="container-fluid">
    <div class="row t-header">
                <header class="t-header__wrapper">
                    <div class="c-logo col-xs-3 col-sm-4 col-md-7 col-lg-8">
                        <a href="#">
                            <img src="img/logo.png" />
                        </a>
                    </div>
                   
                            <div class="c-right-menu col-xs-9 col-sm-8 col-md-5 col-lg-4 text-right">
                                <ul class="list-inline c-right-menu__link">
                                    <li>
                                        <a href="#"><span>Hello</span> Amit Gupta</a>
                                    </li>
                                    <li>
                                        <a href="#">Setting</a>
                                    </li>
                                    <li>
                                        <a href="#">Logout</a>
                                    </li>
                                </ul>

                                <p class="c-right-menu__last-login-details text-left">Last Login 31st July 2015</p>
                            </div>
                
                </header>

                <nav class="navbar navbar-default col-xs-12 col-sm-12 col-md-12 c-navigation">
                
                        <div class="container-fluid">
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header hidden-sm hidden-md hidden-lg">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>

                                <a class="navbar-brand" href="#">Navigation</a>
                            </div>

                            <!-- Collect the nav links, forms, and other content for toggling -->
                            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="#">Dashboard <span class="sr-only">(current)</span></a></li>
                                    <li><a href="#">User</a></li>
                                    <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports <span class="caret"></span></a>
                                        <ul class="dropdown-menu">
                                            <li><a href="#">Action</a></li>
                                            <li><a href="#">Another action</a></li>
                                            <li><a href="#">Something else here</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="#">Separated link</a></li>
                                            <li role="separator" class="divider"></li>
                                            <li><a href="#">One more separated link</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="#">Modules</a></li>
                                    <li><a href="#">Settings</a></li>
                                </ul>

                                <form class="navbar-form navbar-left c-search-form" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control" placeholder="Search">
                                    </div>
                                    <button type="submit" class="btn btn-default glyphicon glyphicon-search c-search-btn"></button>
                                </form>

                            </div><!-- /.navbar-collapse -->
                        </div><!-- /.container-fluid -->
                
                </nav>
            </div> <!-- End t-header -->
            <div class="row t-main">
<body>
  <div class="t-main-wrapper">

                <div class="col-xs-12 col-sm-12 col-md-12 c-heading">
                    <h1>Dashboard</h1>
                </div>

                <div class="t-main-wrapper__content">

                    <div class="col-xs-12 col-sm-3 col-md-2 c-left-sidebar">
                        <div class="c-background-lightgrey c-side-menu">
                            <h2 class="c-label-heading c-side-menu__heading">Side Menu</h2>
                            <ul class="list-unstyled">
                                <li>
                                    <a href="#">Manage Filters</a>
                                </li>
                                <li>
                                    <a href="#">Manage Filters</a>
                                </li>
                                <li>
                                    <a href="#">Manage Filters</a>
                                </li>
                            </ul>
                        </div>

                        <div class="c-background-lightgrey c-systerm-messages">
                            <h2 class="c-label-heading c-systerm-messages__heading">Systerm Messages</h2>
                            <div class="c-systerm-messages__content">
                                <a href="#">Latest Message</a>
                                <ul class="list-unstyled">
                                    <li>
                                        <a href="#">Lorium Ipsum</a>
                                    </li>
                                    <li>
                                        <a href="#">Message Title</a>
                                    </li>
                                </ul>
                                <form>
                                    <div class="form-group">
                                        <input type="text" class="form-control" id="input-text" placeholder="Email">
                                    </div>
                                    <div class="form-group">
                                        <label for="input-textarea">Content</label>
                                        <textarea class="form-control" rows="3" id="input-textarea"></textarea>
                                    </div>
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="blankRadio" id="blankRadio1" value="option1" aria-label="">
                                            To every one
                                        </label>
                                        <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">Send</button>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="c-todo-complete-tab">
                            <!-- Nav tabs -->
                            <ul class="nav nav-tabs c-todo-complete-tablist" role="tablist">
                                <li role="presentation" class="active"><a href="#todo" aria-controls="todo" role="tab" data-toggle="tab">To Do</a></li>
                                <li role="presentation"><a href="#completed" aria-controls="completed" role="tab" data-toggle="tab">Completed</a></li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content c-tab-content">
                                <div role="tabpanel" class="tab-pane active" id="todo">
                                    <ul class="list-unstyled">
                                        <li>
                                            <a href="#">To do will open in Model box</a>
                                            <span>Deadline: Today</span>
                                        </li>
                                        <li>
                                            <a href="#">To do will open in Model box</a>
                                            <span>Deadline: Today</span>
                                        </li>
                                        <li>
                                            <a href="#">To do will open in Model box</a>
                                            <span>Deadline: Today</span>
                                        </li>
                                    </ul>

                                    <div class="c-todo-button">
                                        <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">View All</button>
                                        <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">To Do Config</button>
                                    </div>
                                </div>

                                <div role="tabpanel" class="tab-pane" id="completed">
                                    <ul class="list-unstyled">
                                        <li>
                                            <a href="#">To do will open in Model box</a>
                                            <span>Deadline: Today</span>
                                        </li>
                                        <li>
                                            <a href="#">To do will open in Model box</a>
                                            <span>Deadline: Today</span>
                                        </li>
                                        <li>
                                            <a href="#">To do will open in Model box</a>
                                            <span>Deadline: Today</span>
                                        </li>
                                    </ul>

                                    <div class="c-todo-button">
                                        <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">View All</button>
                                        <button type="submit" class="btn-group btn-group-sm btn-group-md c-xsmall-button" role="group">To Do Config</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-9 col-md-10">
                        <div class="c-background-lightgrey c-report-elements c-report-elements-first">
                            <h2 class="c-label-heading c-report-elements-first__heading">Report Elements</h2>
                            <div class="c-report-elements-first__excel">
                                <h2>Weekly Summary Report</h2>

<div class="table-responsive">
 <table class="table table-bordered c-weekly-summary">
 <tr>
 <th></th>
     <th>Legends</th>
     <th class = 'green'>Green</th>
     <th class = 'amber'>Amber</th>
     <th class = 'red'>Red</th>
     <th></th>
     <th></th>
     <th>Q: Quality</th>
     <th>S: Schedule</th>
     <th>P: Process</th>
     <th>EV: Effort Variance</th>
     <th></th>
     <th></th>
     <th></th>
     <th></th>
     </tr>
 <tr>
     <th id='th'>Time & Material Project Name</th>
     <th>Owner</th>
     <th>Q</th>
     <th>S</th>
     <th>P</th>
     <th>EV</th>
     <th>May Billing Target</th>
     <th>Accured Hrs till last Month</th>
     <th>Accured Hrs in current Month</th>
     <th>Project Plan Hours</th>
     <th>Hours Consumed</th>
     <th>% Remaining</th>
     <th>Hours Needed To Finish</th>
     <th>Completion Date </th>
     <th id='th'>Other Comment </th>
 </tr>
 <?php foreach ($projects as $project) : ?>
 <tr>
   
     <td><?php echo $this->escapeHtml($project['projectName']);?></td>
    <td><?php echo $this->escapeHtml($project['owner']);?></td>
    <?php
     if ($project['quality'] == 1)
      $qualityClass = 'red';
     else if(($project['quality'] >1) && ($project['quality'] <4))
      $qualityClass = 'amber';
     else
     $qualityClass = 'green';
    ?>
     <td class=<?= $qualityClass;?> >
        <?php echo $this->escapeHtml($project['quality']);?>
     </td>
     <?php
     if ($project['schedule'] == 1)
      $qualityClass = 'red';
     else if(($project['schedule'] >1) && ($project['schedule'] <4))
      $qualityClass = 'amber';
     else
     $qualityClass = 'green';
    ?>
     <td class=<?= $qualityClass;?> ><?php echo $this->escapeHtml($project['schedule']);?></td>
     <?php
     if ($project['process'] == 1)
      $qualityClass = 'red';
     else if(($project['process'] >1) && ($project['process'] <4))
      $qualityClass = 'amber';
     else
     $qualityClass = 'green';
    ?>
     <td class=<?= $qualityClass;?> ><?php echo $this->escapeHtml($project['process']);?></td>
      <?php
     if ($project['effortVariance'] == 1)
      $qualityClass = 'red';
     else if(($project['effortVariance'] >1) && ($project['effortVariance'] <4))
      $qualityClass = 'amber';
     else
     $qualityClass = 'green';
    ?>
     <td class=<?= $qualityClass;?> ><?php echo $this->escapeHtml($project['effortVariance']);?></td>
     <td><?php echo $this->escapeHtml(0);?></td>
    <td><?php echo $this->escapeHtml(0);?></td>
     <td><?php echo $this->escapeHtml(0);?></td>
     <td><?php echo $this->escapeHtml($project['estimatedHours']);?></td>
     <td><?php echo $this->escapeHtml($project['totalConsumeHrs']);?></td>
     <td><?php echo $this->escapeHtml(100-($project['percentRemain']));?></td>  
      <td><?php echo $this->escapeHtml(0);?></td>
     <td><?php echo $this->escapeHtml($project['completionDate']);?></td>
     <td><?php echo $this->escapeHtml($project['comment']);?></td>
     
 </tr>
 <?php endforeach; ?>
 </table>
 </div>
<div class="text-right c-download-pdf"> 
<a class="btn btn-success" href="<?php echo $this->url('api', array('action'=>'pdf'));?>">Download PDF</a>
</div>
   
                            </div>
                        </div>

                        <div class="c-background-lightgrey c-report-elements c-report-elements-second">
                            <h2 class="c-label-heading c-report-elements-second__heading">Report Elements</h2>
                            <div class="c-report-elements-second__excel">
                                <h2>Report Title</h2>
                            </div>
                        </div>
                    </div>

                    <!-- Open panel for right sidebar -->
                    <a id="right-sidebar-panel-link" href="#right-sidebar-panel">
                        Right Sidebar Panel
                    </a>
                    <!-- Open panel for right sidebar -->

                    <div id="right-sidebar-panel" class="col-xs-12 col-sm-3 col-md-3 c-right-sidebar">
                        <div class="c-background-lightgrey c-date-calender">
                            <h2 class="c-label-heading c-date-calender__heading">Date Calender</h2>

                            <div class="col-xs-12 col-sm-12 col-md-12 c-date-calender__date-time">
                                <span class="col-sm-6 col-md-6 time">22:15</span>
                                <span class="col-sm-6 col-md-6 date">
                                    07th Aug 2015
                                    <span>
                                        friday
                                    </span>
                                </span>
                            </div>

                            <div class="col-xs-12 col-sm-12 col-md-12 c-date-calender__picker">

                                <div class="c-date-calender__title">
                                    <span></span>
                                    <span>
                                        Calender
                                    </span>
                                </div>

                                <div class="c-date-calender__list" style="overflow:hidden;">

                                    <div class="form-group">

                                        <div class="row">
                                            <div class="col-xs-12 col-sm-12 col-md-12">
                                                <div id="datetimepicker12"></div>
                                            </div>
                                        </div>

                                    </div>

                                </div>

                            </div>
                        </div>

                        <div class="c-background-lightgrey c-quick-visula-linkes">
                            <h2 class="c-label-heading c-quick-visula-linkes__heading">Quick Visula Linkes</h2>
                        </div>
                    </div>

                </div>
            </div> <!-- End t-main-wrapper -->
<?php echo $this->headScript()
            ->prependFile($this->basePath('js/panelslider.js'))
        ; ?>

 